--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/GiftCodeID
build-by-default: true
branches:
- main
projects:
  GiftCodeID:
    path: ""
    icon: 1611205.png
        libs:
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.1.0
        branch: master
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
        branch: master
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
        branch: master
      - src: NurAzliYT/FormAPI/FormAPI
        version: ^1.0.0
        branch: main
    lint:
      phpstan: false
...
