--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/GiftCodeID
build-by-default: true
branches:
- main
projects:
  GiftCodeID:
    path: ""
    icon: 1611205.png
        libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
    lint:
      phpstan: false
...
