name: GiftCodeID
main: NurAzliYT\GiftCode\GiftCode
api: [3.0.0], [4.0.0], [5.0.0]
version: 1.0.0
author: NurAzliYT
depend: [BedrockEconomy, EconomyAPI]
description: Plugin Gift Kode Bahasa Indonesia

virions:
- FormAPI

permissions:
  giftcode.createcode:
    description: Permission untuk membuat kode
    default: op
  giftcode.entercode:
    description: Permission untuk enter kode
    default: true
