name: GiftCode-GB
main: NurAzliYT\GiftCode\GiftCode
api: 5.0.0
version: 1.0.0
author: NurAzliYT
depend: [BedrockEconomy, MultiWorld, HumanNPC]
description: Plugin Gift Code English
depend: ["BedrockEconomy, CoinAPI"]

virions:
- FormAPI

permissions:
  giftcode.createcode:
    description: Permission untuk membuat kode
    default: op
  giftcode.entercode:
    description: Permission untuk enter kode
    default: true
